services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    networks: [ kafka-network ]
    ports:
      - "9092:9092" # For connecting from container
      - "29092:29092" # For connecting from host machine
    environment:
      # --- Modern KIP-500 mode ---
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # --- Listeners ---
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # --- Required for single-node cluster ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka-network
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

#  producer:
#    build:
#      context: ./producer
#    image: producer:0.0.1-SNAPSHOT
#    container_name: kafka-producer
#    networks: [ kafka-network ]
#    depends_on: [ kafka ]
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092

networks:
  kafka-network:
    driver: bridge